"""add local_path to repository

Revision ID: 121505947bd0
Revises: 4aab78ae017a
Create Date: 2026-07-29 19:50:07.970786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121505947bd0'
down_revision: Union[str, Sequence[str], None] = '4aab78ae017a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('local_path', sa.String(), nullable=False))
    op.alter_column('repository', 'github_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repository', 'github_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('repository', 'local_path')
    # ### end Alembic commands ###
